# Generated by Django 5.2 on 2025-04-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studemt',
            new_name='Student',
        ),
    ]
