# Generated by Django 5.2 on 2025-04-30 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_teacher_adhaar_number_teacher_bio_teacher_facebook_and_more'),
        ('course', '0010_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.coursecategory'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.coursesubcategory'),
        ),
    ]
