# Generated by Django 5.2 on 2025-04-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_teacher_category_teacher_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
