# Generated by Django 5.2 on 2025-04-30 09:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_student_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
