# Generated by Django 5.2 on 2025-04-30 09:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_student_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
