# Generated by Django 5.2 on 2025-05-01 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_teacher_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_video', models.FileField(upload_to='demo/')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo', to='account.teacher')),
            ],
        ),
    ]
