# Generated by Django 5.2 on 2025-04-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_coursesubcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesubcategory',
            name='description',
        ),
    ]
