# Generated by Django 5.2 on 2025-04-29 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_student_user_teacher_user'),
        ('course', '0007_course_category_course_discount_price_course_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='account.teacher'),
            preserve_default=False,
        ),
    ]
