# Generated by Django 5.2 on 2025-04-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
