# Generated by Django 5.2 on 2025-05-01 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_lesson_options_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subcategory',
            field=models.ForeignKey(default='Beginner', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.coursesubcategory'),
        ),
    ]
