# Generated by Django 5.2 on 2025-10-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_course_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='watch_time',
            field=models.IntegerField(default=0),
        ),
    ]
