# Generated by Django 5.2 on 2025-10-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_progress_watch_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
